export const GET_STEPS_SUCCESS = "GET_STEPS_SUCCESS";
export const SAVE_STEP_SUCCESS = "SAVE_STEP_SUCCESS";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const DELETE_STEP_SUCCESS = "DELETE_STEP_SUCCESS";